### ISSUE TITLE
handle[p].copy(buf, offset)  is not a function

### ISSUE THREAD

**Issue by Cyrillius** [inando/ads.js#6]
Hello!

I am a student in industrial system engineering.

I am using your library to design an Angular.js HMI  connected trough ADS to a TWINCAT PLC.

Unfortunately I have an error when I try to write something.

Here is the error I have:
```
C:\Users\Administrateur\Documents\Github\angulhmi\node_modules\ads\ads.js:905
            handle[p].copy(buf, offset);
                      ^
TypeError: undefined is not a function
    at getBytesFromHandle (C:\Users\Administrateur\Documents\Github\angulhmi\node_modules\ads\ads.js:905:23)
    at Object.<anonymous> (C:\Users\Administrateur\Documents\Github\angulhmi\node_modules\ads\ads.js:259:13)
    at Object.<anonymous> (C:\Users\Administrateur\Documents\Github\angulhmi\node_modules\ads\ads.js:385:24)
    at Object.getWriteReadResult (C:\Users\Administrateur\Documents\Github\angulhmi\node_modules\ads\ads.js:633:8)
    at Object.analyseResponse (C:\Users\Administrateur\Documents\Github\angulhmi\node_modules\ads\ads.js:211:32)
    at Object.checkResponseStream (C:\Users\Administrateur\Documents\Github\angulhmi\node_modules\ads\ads.js:152:33)
    at Socket.<anonymous> (C:\Users\Administrateur\Documents\Github\angulhmi\node_modules\ads\ads.js:105:29)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
```

Here is the javascript code:
```javascript
var client = this.ads.connect(options, function() {
    this.write(myHandle, function(err) {
        this.read(myHandle, function(err, handle) {
            console.log(handle.value);
	    this.end();
        });
    });
});
```

Here is the content of options:
```javascript
{ host: '149.156.138.72',
  amsNetIdTarget: '5.10.0.204.1.1',
  amsNetIdSource: '192.168.1.101.1.1',
  port: 48898,
  amsPortSource: 32905,
  amsPortTarget: 801 
}
```

Here is the content of myHandle:
```javascript
{ symname: '.I_start',
  bytelength: 1,
  propname: 'value',
  value:  true  
}
```

Can you help me ?
I think the problem is linked to the use of the framework angular.js

**Comment by tdjordan** [comment]
Are you using TwinCAT 2 or TwinCAT 3?
